### ISSUE TITLE
please update revisions of dependencies

### ISSUE THREAD

**Issue by ssured** [duizendnegen/ember-cli-deploy-azure#11]
With ember-cli 2.14 a lot of deprecation warnings are raised:

`DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/Users/s...3/node_modules/ember-cli-deploy-azure/node_modules/ember-cli-deploy-build/index.js:4:15)`

Newer versions of `ember-cli-deploy-build` and `ember-cli-deploy-revision-data` do not trigger the warning, and are AFAIK fully backwards compatible. Thanks!

**Comment by ssured** [comment]
From my package.json this is recent:

```
    "ember-cli-deploy-build": "^1.1.0",
    "ember-cli-deploy-revision-data": "^1.0.0",
```

**Comment by duizendnegen** [comment]
Thanks - updated, published to `npm`. In the future you're also warmly invited to make a PR for this ;)

**Comment by ssured** [comment]
:+1: te druk met het updaten van ember cli naar 2.14 voor een groot project, slecht excuus... Dankjewel voor je plugin!
