### ISSUE TITLE
ember-deploy is now ember-cli-deploy

### ISSUE THREAD

**Issue by LevelbossMike** [duizendnegen/ember-cli-deploy-azure#2]
Hi @duizendnegen!

ember-deploy has been renamed [ember-cli-deploy](ember-cli/ember-cli-deploy) and will be the officially supported tool for deploying ember applications with ember-cli.

I already checked [ember-deploy-redis](levelbossmike/ember-deploy-redis) and [ember-deploy-s3](levelbossmike/ember-deploy-s3) and they are working correctly when used with ember-cli-deploy's master version. see https://github.com/ember-cli/ember-cli-deploy/issues/68

The next release will be 0.4.0 which should not break the existing api but one never knows ;)

Please let me know if I can be of any help porting your addon if any porting needs to be done.

One change for example expects a config/deploy.js file instead of an deploy.json file in the root folder of your project, maybe this will cause issues with your addon?

Best regards and thanks for your hard work on this addon!

Mike

**Comment by duizendnegen** [comment]
Thanks Mike, I'll keep in touch about the mergeability!
