### ISSUE TITLE
setting `gzip: true` results in garbled css/js

### ISSUE THREAD

**Issue by jamesdixon** [duizendnegen/ember-cli-deploy-azure#6]
Hi, I attempted to use the `gzip: true` and unfortunately, I'm being returned a bunch of garbled JS and CSS from Azure. Have you encountered this?

Cheers,
James

**Comment by duizendnegen** [comment]
I did, and I decided not to gzip when I encountered it... there's some articles floating complaining about Azure and gzip, but I think they have to do with CDNs not properly supporting them. Not sure.
In https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js#L2950 it indicates accepting an options hash, in which you can set the content encoding. http://stackoverflow.com/questions/23263129/does-windows-azure-blob-storage-support-serving-compressed-files-similar-to-amaz indicates that this value has to be `GZIP`.

In https://github.com/duizendnegen/ember-deploy-azure/blob/master/lib/azure-assets.js#L114 ember-deploy-azure tries to determine whether to mark the file as gzipped. Possibly that's not triggered succesfully, or the value `gzip` is not equal to `GZIP`? Feel free to give it a spin, otherwise I'll probably look into it in a week or so.

**Comment by jamesdixon** [comment]
Yeah, I've read a couple of things and it's honestly a bit confusing as to whether it's supported or not. However, I did some debugging and it almost seems as if `ember-cli-deploy` isn't gzipping the files. I came across [this thread](https://github.com/ember-cli/ember-cli-deploy/issues/122), which indicated something similar is happening with the `ember-deploy-s3` plugin as well. It also seems that 0.5.0 may have remedied some of this based on the [description in the PR](https://github.com/ember-cli/ember-cli-deploy/pull/179).

Last but not least, I just saw [this thread on the Microsoft site](http://feedback.azure.com/forums/169397-cdn/suggestions/1074433-automatic-http-compression-on-azure-blob-cdn-gzip) that indicates the CDN will automatically handle GZIPing content from Blob Storage.

**Comment by duizendnegen** [comment]
It should gzip at https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/tasks/assets.js#L22

0.5.0 will most likely remedy some of these issues - I'm starting work on that upgrade soon as well.

Will keep this issue open to track progress

**Comment by jamesdixon** [comment]
Long time, @duizendnegen! 

Just revisiting this with the latest version of `ember-cli-deploy` and sadly having the same problem. First off, Azure now supports gzipping files on the fly, which is great. Unfortunately, it only does it [for files that are less than 1MB](https://azure.microsoft.com/en-us/documentation/articles/cdn-improve-performance/) (see the comments). Sadly, my `vendor.js` file ends up nearly being 3MB. I'd like to get that down eventually, but still probably won't ever be able to get it under 1MB. That said, I needed to upload my own gzipped version. 

I attempted to use the `ember-cli-deploy-gzip` plugin, which appears to gzip the files properly, but when I load my page, I get an `Unexpected token ILLEGAL` error. Further investigation reveals that javascript files aren't being decoded. However, CSS files appear to work fine. I tried setting the `content-encoding` header manually, but still no luck.

Have you revisited this at all?

Cheers.

**Comment by duizendnegen** [comment]
Yep, I have had a similar issue - very unfortunate that the gzip-on-the-fly thing is only for <1mb.

I have had success in the past with https://github.com/duizendnegen/ember-cli-deploy-azure-blob/blob/master/index.js#L122 - as per https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js#L2814 that should suffice to set gzip appropriately. Note, _should_.

The `ember-cli-deploy-azure-blob` side of things might be out of date for this specific part - a PR is welcome for setting a bool whether gzip is enabled or not and the plugin reading that to inform its decision on setting this encoding header.

**Comment by duizendnegen** [comment]
Let me know if https://github.com/duizendnegen/ember-cli-deploy-azure-blob/pull/2 solved this - if you are able, could you continue the conversation with MSFT in those comments to get some feedback of them also supporting >=1mb in the near future? (for me, that's where really the gzip benefits lie...)

**Comment by jamesdixon** [comment]
Yes, it is resolved -- I was the one who submitted the PR, so it better work ;)
