### ISSUE TITLE
Deprecation: require('ember-cli/lib/errors/silent')

### ISSUE THREAD

**Issue by Energiz0r** [duizendnegen/ember-cli-deploy-azure#7]
Just wanted to note that there is a deprecation in azure-index.js and azure-assets.js.

`var SilentError = require('ember-cli/lib/errors/silent');`

**Comment by duizendnegen** [comment]
Thanks - we're building towards a new version of ember-cli-deploy - when https://github.com/ember-cli/ember-cli-deploy/pull/179 gets merged, you'll see the deprecation disappear.
